### PR TITLE
Capture training data for traffic light classifier

### PR DESCRIPTION
**Pull request by manu291**
This PR is to be reviewed after PR #3 and PR #7, as it is based on top of the corresponding branches.
It makes tl_detector.py able to save images from the camera in directories structured as expected by the script `retrain.py` from tensorflow. The saved images will make possible to fine tune an image classifier to infer the states of the traffic lights.
To test it:
```bash
roslaunch launch/styx.launch get_light:=oracle record_path:="/path-where-to-save-the-captures/"
```
Check Camera in the simulator and uncheck Manual. Then when the car comes close to the traffic lights, it starts recording the images.

It uses the traffic light state given by topic `/vehicle/traffic_lights` to automatically save each image in the corresponding subdirectory. There are some rare mistake sometimes though because of minor timing issue. So the data actually needs to be visually curated after recording, but I think the tool is good enough. I have already used it to gather around 5,000 images, which I'll post on slack.
Also sometimes it records images where the color of the traffic light is not visible but still assign it to a known state. In such a case I just move manually the images to the `4_unknown` subdirectory.

### CODE REVIEW

**Comment by Labonneguigue** [comment]
Need resolving the conflicts

**Comment by scs50** [comment]
The code did not work on my Docker Environment. First the vehicle would only run in manual mode. The second issue is that it would create the correct folder structure to save the TL images to, but there would be no images in the folders. It might be a Docker specific issue.

**Comment by manu291** [comment]
As mentioned in slack, the docker container needs the library pillow to be upgraded for the camera data to be properly streamed. You can upgrade with:
```
pip install pillow --upgrade
```
I was not able to reproduce the bug that prevents the car from running autonomously. When I tested with docker the car would run automatically when unchecking "Manual".

**Review by Labonneguigue — CHANGES_REQUESTED** [review]
Shouldn't be commented out.
That's why it doesn't create the images

**Comment by Labonneguigue** [comment]
Enabling the camera screws up everything for me. The car doesn't follow the path anymore.

**Comment by manu291** [comment]
Please @Labonneguigue and @scs50 give as much details as possible about that bug (the car that doesn't drive correctly when tl_detector.py is launched) because I am not able to reproduce the bug. It works fine for me both in docker and VM.
Could you please give detailed description of the environment? docker/VM/native how did you install it?
Do you get any log message in the ROS master?
Do you get any traceback?
It is very hard (or impossible) for me to debug since I cannot reproduce the bug.
Thanks

**Comment by Labonneguigue** [comment]
Environment: Ubuntu 16.04 Native on Lenovo x230 (if you want to compare the specs)
The problem for me is when I activate the camera.
The video bellow will try to explain it better. Look at the waypoints.

https://youtu.be/BCRp_rgdAJA

**Review by Labonneguigue — APPROVED** [review]

**Comment by Labonneguigue** [comment]
I found a solution. I'll post it in the #11 PR.
It is effectively reducing the publishing rate of the waypoint_updater

**Pull request merged**
